### ISSUE TITLE
Any user can prevent a shutdown

### ISSUE THREAD

**Issue by ghost** [CGWilliam/PennyBot#2]
Sorry if I'm misunderstanding the code

since `find_penny_comment(...)` operates on multiple comments per execution, if a mod makes a comment requesting shutdown, followed by a user requesting shutdown (within up to 70 seconds), it will reset `shutdown` back to `False`, negating the shutdown request

This would probably require a tiny bit of a re-write (as the comment needs to be added to the processed list so it won't shutdown again when restarted, so `sys.exit(...)` can't just be thrown in there), maybe best saved for a PennyBot V2.5?

``` python
def find_penny_comment(flat_comments, processing, mods):
    # ...
    for comment in flat_comments:
        # ...
        if comment.id in processing:
            # ...
            for current in list:
                # ...
                if "pennybot," in current:
                    # ...
                    elif current.startswith("shutdown"):
                        # ...
                        shutdown = False
                        # ...
                        if commentauthor in mods or commentauthor == "Weerdo5255":
                            shutdown = True
                        # ...

# ...
# ...

while True:
    # ...
    commentid = find_penny_comment(flat_comments, processing, mods)
    time.sleep(70)
```

**Comment by CGWilliam** [comment]
I see what you mean, and the big issue like you pointed out was having the comment still be added to the processed list. 

The best solution I can think of at the moment is making the `already_done` list a global and giving the shutdown command the appropriate code to use it and then initiate shutdown. This however does not break the entire try except in which the Penny code is inside of. 

I'm going to have to think about this some more, thanks for spotting it! Hopefully we won't have a situation where this would come into play, but it is a glaring error in the logic.

**Comment by RascalTwo** [comment]
In my testing, the shutdown command doesn't work even when this bug mentioned above isn't present.

```
Found a comment at: Mon Jul 11 13:50:49 2016
redwing36
https://www.reddit.com/r/RWBY/comments/4ryouf/whose_line_is_it_saturday_july_09_2016/
['Emergency Shutdown Initiated! Bye!']
I ran successfully at: Mon Jul 11 13:50:52 2016
time.sleep(5)
Found a comment at: Mon Jul 11 13:50:57 2016
redwing36
https://www.reddit.com/r/RWBY/comments/4ryouf/whose_line_is_it_saturday_july_09_2016/
['Emergency Shutdown Initiated! Bye!']
I ran successfully at: Mon Jul 11 13:50:57 2016
time.sleep(5)
Found a comment at: Mon Jul 11 13:51:02 2016
redwing36
https://www.reddit.com/r/RWBY/comments/4ryouf/whose_line_is_it_saturday_july_09_2016/
['Emergency Shutdown Initiated! Bye!']
I ran successfully at: Mon Jul 11 13:51:03 2016
```

The reason is due to the fact that the `shutdown` variable within the `find_penny_comment()` method is not the global `shutdown` variable.

Adding `global shutdown` within `find_penny_comment()` method anywhere before the actual change to `shutdown` will work.

> Right after the method declaration is where all the `global` statements are usually added, but you could add it the line before `shutdown` gets changed. So either

``` Python

def find_penny_comment(flat_comments, processing, mods):
    global shutdown
    # ...
```

or

``` Python
def find_penny_comment(flat_comments, processing, mods):
    # ...
    for comment in flat_comments:
        # ...
        if comment.id in processing:
            # ...
            for current in list:
                # ...
                if "pennybot," in current:
                    # ...
                    elif current.startswith("shutdown"):
                        global shutdown
```

would work, as seen here:

```
➜  PennyBot git:(master) ✗ python3 Main.py
Found a comment at: Mon Jul 11 14:00:33 2016
redwing36
https://www.reddit.com/r/RWBY/comments/4ryouf/whose_line_is_it_saturday_july_09_2016/
['Emergency Shutdown Initiated! Bye!']
I ran successfully at: Mon Jul 11 14:00:37 2016
time.sleep(5)
➜  PennyBot git:(master) ✗ 
```

---

As for the bug itself, it's a legit bug, as seen here:

```
➜  PennyBot git:(master) ✗ python3 Main.py
Found a comment at: Mon Jul 11 14:02:22 2016
redwing36
https://www.reddit.com/r/RWBY/comments/4ryouf/whose_line_is_it_saturday_july_09_2016/
['Emergency Shutdown Initiated! Bye!']
Found a comment at: Mon Jul 11 14:02:26 2016
Rascal_Two
https://www.reddit.com/r/RWBY/comments/4ryouf/whose_line_is_it_saturday_july_09_2016/
['You are not Pyrrha!']
I ran successfully at: Mon Jul 11 14:02:28 2016
time.sleep(5)
Found a comment at: Mon Jul 11 14:02:33 2016
redwing36
https://www.reddit.com/r/RWBY/comments/4ryouf/whose_line_is_it_saturday_july_09_2016/
['Emergency Shutdown Initiated! Bye!']
Found a comment at: Mon Jul 11 14:02:35 2016
Rascal_Two
https://www.reddit.com/r/RWBY/comments/4ryouf/whose_line_is_it_saturday_july_09_2016/
['You are not Pyrrha!']
I ran successfully at: Mon Jul 11 14:02:35 2016
time.sleep(5)
```

The solution is - without having to rewrite any major bits of code - to remove the `shutdown = False` line [here](https://github.com/CGWilliam/PennyBot/blob/7d9b114101d00980110f41764027c12ba62845e1/Main.py#L730).

As you can see, it works:

```
➜  PennyBot git:(master) ✗ python3 Main.py
Found a comment at: Mon Jul 11 14:06:15 2016
redwing36
https://www.reddit.com/r/RWBY/comments/4ryouf/whose_line_is_it_saturday_july_09_2016/
['Emergency Shutdown Initiated! Bye!']
Found a comment at: Mon Jul 11 14:06:20 2016
Rascal_Two
https://www.reddit.com/r/RWBY/comments/4ryouf/whose_line_is_it_saturday_july_09_2016/
['You are not Pyrrha!']
I ran successfully at: Mon Jul 11 14:06:21 2016
time.sleep(5)
➜  PennyBot git:(master) ✗ 
```

**Comment by CGWilliam** [comment]
That works, I'll commit it! 

I don't have much experience with global variables, I don't like to use them. Usually because they cause issues like this.
