### ISSUE TITLE
Duplicate lines

### ISSUE THREAD

**Issue by austinmulvihill** [CGWilliam/PennyBot#5]
Commands.py lines 23 and 32 are duplicate if statements.
Also, I would recommend "Ahem:" or "Ahem."

**Comment by RascalTwo** [comment]
Direct links for convenience:
- [23](https://github.com/CGWilliam/PennyBot/blob/0e2c0632ad447e3067e94ae005b78f82fa3c0e66/Commands.py#L23)
- [32](https://github.com/CGWilliam/PennyBot/blob/0e2c0632ad447e3067e94ae005b78f82fa3c0e66/Commands.py#L32)

Looks like it is defiantly a duplicate command.

---

I personally don't have any preference on "Ah hem" vs "Ahem".

I thought it was an attempt to replicate Pennys tone of voice by adding the space and additional "h", but it could be another typo.

**Comment by CGWilliam** [comment]
Resolved.
