### ISSUE TITLE
Command misspelling

### ISSUE THREAD

**Issue by austinmulvihill** [CGWilliam/PennyBot#6]
Command.py line 83 I believe this is supposed to be pervert not pervet

**Comment by RascalTwo** [comment]
[Direct link](https://github.com/CGWilliam/PennyBot/blob/0e2c0632ad447e3067e94ae005b78f82fa3c0e66/Commands.py#L83) for convenience.

Just about the worse place to have a misspelling too, in the trigger.

---

See [here](https://help.github.com/articles/getting-permanent-links-to-files/) on how to make the URL permanent after clicking on the line number when looking at code.

**Comment by CGWilliam** [comment]
Yep no spellcheck in the IDE still. Corrected.
