### ISSUE TITLE
Text spelling

### ISSUE THREAD

**Issue by austinmulvihill** [CGWilliam/PennyBot#7]
Commands.py line 133 I believe it should be Katanas not Katana's

**Comment by RascalTwo** [comment]
[Direct link](https://github.com/CGWilliam/PennyBot/blob/0e2c0632ad447e3067e94ae005b78f82fa3c0e66/Commands.py#L133) for convince, and it should be "Katanas", as currently it's "Katana is".

**Comment by CGWilliam** [comment]
Got it.
